### ISSUE TITLE
Inference personal dataset

### ISSUE THREAD

**Issue by czx94** [zhyever/Monocular-Depth-Estimation-Toolbox#10]
Hi Zhenyu, do you have some scripts to run some test on my own data? If there is, can you give a simple example? Thanks a lot!

**Comment by zhyever** [comment]
For now, you should write your custom dataset class, such as MyCustomDataset, following the provided KITTIDataset or NYUDataset in the folder `depth/datasets/`. You can also inherit them for simplicity. After registering them following [docs](https://mmcv.readthedocs.io/en/latest/understand_mmcv/registry.html), you can set up your own config file to test on your dataset.

Some points: I will refactor the dataset classes since, as you can see, there is a custom.py in the dataset folder but not used as a base class for other datasets. After that, I will provide unified docs about the dataset class (definitely including the custom dataset) and transform pipeline. Busy with other projects, I will try to finish all these plans ASAP.

**Comment by zhyever** [comment]
I add several supports for custom dataset training. Close this issue for now.
