### ISSUE TITLE
About the Classification head in BinsFormer

### ISSUE THREAD

**Issue by ruili3** [zhyever/Monocular-Depth-Estimation-Toolbox#12]
Hi Zhenyu,

I read your paper BinsFormer, the result looks very impressive!

I have a question on the proposed classfication head, I wonder what exactly is the scene type the classification head aims to specify, and where does the supervising signal come from in KITTI and NYUDepth datasets, etc.

Moreover, wish you can release the code in the coming days so the followers including me can do some explorations upon your nice work. Thank you :D

**Comment by zhyever** [comment]
Thanks for your attention to our work.

Keep in mind that the major insight of BinsFormer is to predict adaptive bins in a more elegant manner. One of the points proposed in our paper is the multi-scale interaction with per-pixel representations, which makes sense and is inevitable. Another useful information for bins prediction may come from semantic knowledge. However, the semantic info can be discarded during the forward propagation of the encoder-decoder (the feature tends to be depth-related instead of semantic). So, we add the scene classification query to learn the semantic info explicitly. This GT label can be obtained from the folder name. For example, a training image in NYU has path `data/nyu/bathroom_0001/rgb_00000.jpg`, and its scene label is `bathroom`. In KITTI, we do not use the scene understanding task since all images come from outdoor settings, which are hard to classify into different classes.

As for codes, I am currently busy with other projects, but I will release BinsFormer ASAP.

**Comment by zhyever** [comment]
Close for now. Feel free to re-open for further discussion.

**Comment by nonononentity** [comment]
Hello, 
Thank you for your answer.
And why is the parameter "classify"  not used in all your config files?
I find it in "Based-decode_heads class" and I can not find the demo.

**Comment by zhyever** [comment]
That's a parameter for the cls.-based depth estimation method, which is presented in the BinsFormer paper (see the ablation studies). So when I release the BinsFormer, you can find them in the configs. :D

**Comment by nonononentity** [comment]
Nice, Look forward your work, thank you.
