### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by Waterman0524** [zhyever/Monocular-Depth-Estimation-Toolbox#15]
hello, when i use slurm to train, i have a problem.
![image](https://user-images.githubusercontent.com/67633587/165698849-23394d33-525d-4e30-a17f-a4e1a9126aa1.png)
It stopped

**Comment by zhyever** [comment]
I think it may be a problem related to the git repo. https://komodor.com/blog/solving-fatal-not-a-git-repository-error/ may provide some reasons for it. I cannot ensure that it is related to our codes since I have not tested on slurm. If you figure out there are bugs in our codes, feel free to make a pr.

**Comment by zhyever** [comment]
Close for now.
