### ISSUE TITLE
Why is your idea so similar to masked attention mask transformer https://arxiv.org/abs/2112.01527 .

### ISSUE THREAD

**Issue by Shahrazad122** [zhyever/Monocular-Depth-Estimation-Toolbox#30]
Why is your idea so similar to masked attention mask transformer https://arxiv.org/abs/2112.01527
![1](https://user-images.githubusercontent.com/108800380/177531626-5fa25955-c15b-45da-98ff-37b5948756d7.png)
![2](https://user-images.githubusercontent.com/108800380/177531642-00c3b682-f997-418b-93fb-261b633a910d.png)
![3](https://user-images.githubusercontent.com/108800380/177531649-8d1023be-6066-4a30-ad7d-1e449e9651fd.png)
.

**Comment by zhyever** [comment]
Since this work is motivated by Max-DeepLab, MaskFormer, Mask2Former, and PanopticFCN, this line of research in segmentation. We demonstrate a similar double-stream structure can work well (seems very well) in depth estimation. Based on this, it is interesting to associate these two scene understanding tasks in a unified structure.
