### ISSUE TITLE
About sigloss

### ISSUE THREAD

**Issue by djx99** [zhyever/Monocular-Depth-Estimation-Toolbox#4]
In your paper, I find the a in sigloss is set to 10 following Bhat et al., 2021.
But in sigloss.py the loss_weight is 1.0 ?

**Comment by zhyever** [comment]
Since DepthFormer is trained with only SigLoss, the loss_weight is irrelevant. Moreover, the loss_weight=1 in sigloss.py is a default setting. if it needs to be changed, please set it in the config as: https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/b3df83fe70aefed71143c43d51e8b3538c705367/configs/_base_/models/adabins.py#L13.

**Comment by djx99** [comment]
thank you. I didn't see it
