### ISSUE TITLE
KITTI Evaluation

### ISSUE THREAD

**Issue by ldkong1205** [zhyever/Monocular-Depth-Estimation-Toolbox#62]
Hi @zhyever, thank you so much for open-sourcing this excellent repository! I am new to depth estimation. I have a question regarding the evaluation of the KITTI dataset.

For the self-supervised depth estimation methods like [MonoDepth2](https://github.com/nianticlabs/monodepth2), the models are evaluated with a ground-truth file named `gt_depths.npz`. For evaluations in your repository, however, it seems that we need to download the annotated depth ground-truth.

I would like to ask what is the difference between these two. Can I evaluate your models in a way just like the self-supervised depth estimation methods? Besides, will the size of evaluation images affect the evaluation performance? For example, can I evaluate your DepthFormer model trained with the 1241 × 376 resolution with evaluation images of size 640 x 192?

Thanks again for your contribution in this area. Looking forward to your reply!

**Comment by zhyever** [comment]
Thanks for your interest.

I read the codes of MonoDepth2 a long time ago, so the views below can be not correct but only from my own understanding. For unsupervised depth estimation, since there is no GT, the model output can only be in a range of 0-1, as an output of a sigmoid function. That is a sort of relative depth. When evaluating, we need to apply the mean depth to scale the predicted depth range to the real depth range for calculating metrics between GT. 

For the GT `gt_depths.npz`. I remember the evaluation of self-supervised depth and supervised depth is not aligned till now. You can refer to the Toyota repos/papers of PackNet3D for some details, where I remember the authors highlight this issue and also modify something about it in their codes. In short words, the GT for supervised depth is more elaborate and accurate, but the GT for self-supervised depth is closer to the raw point cloud projections (maybe it is).

So, if you'd like to evaluate our models in a self-supervised manner, that can be implemented directly to calculate metrics with the `gt_depth.npz` but skip the scaling stage since the supervised model gives a real depth. Also I need to highlight, when you evaluate your DepthFormer model trained with the 1241 × 376 resolution with evaluation images of size 640 x 192, you will get totally wrong depth results. Not only for DepthFormer but all supervised methods cannot work for evaluation with various resolutions. I recommend our paper STMono3D (Unsupervised Domain Adaptation for Monocular 3D Object Detection via Self-Training), where we analyze this problem called depth shift in a mono3d setting, but I observed this problem also exists in monodepth.

**Comment by ldkong1205** [comment]
Hi @zhyever, thank you for your prompt and detailed reply! Your explanation resolves my questions and helps me understand the difference between supervised and self-supervised depth estimation better.

**Comment by zhyever** [comment]
There is a long time since I have not studied self-supervised methods. So, if there is something wrong, hope that you can point it out here, avoiding misleading other people seeing this issue. Thanks, hope that can be helpful for you. 😄

**Comment by ldkong1205** [comment]
> There is a long time since I have not studied self-supervised methods. So, if there is something wrong, hope that you can point it out here, avoiding misleading other people seeing this issue. Thanks, hope that can be helpful for you. 😄

Sure, I will provide more details of this after testing the models. Thanks again!
